apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: app2
  source:
    path: "HelmCharts/MyChart2"
    repoURL: "git@github.com:1100-git/argo-k8s.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values_dev.yml
      parameters:
      - name: "container.image"
        value: httpd:latest

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true